
 - name: Add ec2-user for Amazon Linux in docker group
   ansible.builtin.user: 
    name: ec2-user
    append: true
    groups: docker

# Need to logout & login after adding user to group (above code is analogous to 'usermod', so need to relogin to shell)


