---
# - name: Get the control plane node facts
#   ansible.builtin.debug:
#     msg: "{{ hostvars[groups['cpnodes'][0]] }}"
#   tags: node-network-setup

- name: Join secondary node with the primary control plane node
  ansible.builtin.command: "{{ kubeadm_join_cmd }}" 
  tags: node-network-setup