---
- name: Copy admin.conf to an accessible location on primary node
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/admin.conf
    flat: true
  delegate_to: localhost
  run_once: true
  tags: post-setup

- name: Ensure /etc/kubernetes directory exists
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: post-setup
  
- name: Move admin.conf from primary node to worker nodes
  become: true
  ansible.builtin.copy:
    src: /tmp/admin.conf
    dest: /etc/kubernetes/admin.conf
    owner: root
    group: root
    mode: '0600'
  tags: post-setup